### ISSUE TITLE
User Friendly Task ID

### ISSUE THREAD

**Issue by aawadall** [aawadall/PyProjMan#6]
Define user friendly Task IDs, such that users can identify tasks while manipulating them using the text UI

**Comment by aawadall** [comment]
This will require some sort of mapping function

**Comment by aawadall** [comment]
required fix:
to map the existing UUID to an ID that is 4 digits max

**Comment by burhania2** [comment]
Would an increment work? i.e. each instance of a task object has an id of one higher then the previous task. 
Or would this be unviable for  for later tasks?

**Comment by burhania2** [comment]
import itertools

class task():
    newid = itertools.count(1)
    def __init__(self):
        self.id = next(self.newid)

**Comment by aawadall** [comment]
Why not.
Try to put it in the __init__ and test it please

**Comment by burhania2** [comment]
Do I test using UnitTesting?

**Comment by aawadall** [comment]
If you can. If not we can have a second round of unit tests

**Comment by burhania2** [comment]
I could not test from the parser as we don't have a way  (or I don't fully know how)  to track id yet
but I added a bunch o instances of tasks at the end of file and printed the task id to screen which worked in giving me a task id for each instance starting with zero.

**Comment by burhania2** [comment]
`
import itertools

class Task:
    """Building block of a project plan"""
    type = "Task Element"
    taskid = itertools.count()

    def __init__(self, name=None):
        # Basic Information
        self._id = next(self.taskid)
        self._name = name


a= Task()
print(a._id)
b= Task()
v = Task()
ssd=Task()
print(ssd._id)
ter= Task()
qwe = Task()
re = Task()
print(re.id)

print(a._id)
`

**Comment by aawadall** [comment]
nice, can you commit this change?

**Comment by burhania2** [comment]
Did I screw something up?

**Comment by burhania2** [comment]
I ended up with a fork

**Comment by aawadall** [comment]
@burhania2 
can you create a pull request?
